// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.johnpurchase.matreq.model;

import java.lang.String;

privileged aspect Purchaser_Roo_JavaBean {
    
    public String Purchaser.getName() {
        return this.name;
    }
    
    public void Purchaser.setName(String name) {
        this.name = name;
    }
    
}
